### ISSUE TITLE
Curatati codul!

### ISSUE THREAD

**Issue by sica07** [andreimihalcea97/PHP#1]
Baieti, aveti haos in cod.
Codul nu e formatat.
Tone de bucati de cod comentat.
Echo-uri uitate aiurea prin cod.
`describe`-uri in model.
Aveti o clasa Model in src/ (asa cum si trebuie) dar mai aveti una si in app/
Aveti in src/GameModel.php dar il aveti si in app/Models (asa cum ar si trebui).

Ia numa' sa faceti asa ceva la munca: sa faceti commit la cod cu die-uri, echo-uri si clase trantite aiurea, apoi ceilalti colegi care lucreaza cu voi la proiect vor face git pull si dintr-o data se trezesc cu toate echo-urile si die-urile si clasele aruncate aiurea (ma refer la GameModel in src si Model in app). Sa vedeti numa cum in cateva secunde o sa vi se urce toti in cap.
Curatati codul inainte de a face commit. Macar scoateti die-urile si echo-urile care au scop de debugging.

**Comment by AlexGligore** [comment]
Am sters tot ce era in plus, majoritatea codului problema era cod vechi uitat in repo.
A mai ramas doar un echo in Router de care ne folosim pentru debug in views. O sa dispara inainte de prezentarea proiectului.
Multumim pentru semnalarea problemelor!

**Comment by sica07** [comment]
ok

În lun., 4 feb. 2019 la 21:27, Alex Gligore <notifications@github.com> a
scris:
